##############################DESIGUALDAD#########################################
library(funcionesINE)
library(xlsx)
library(xlsxjars)
documento <- leerLibroNormal('/home/hugo/Documents/Encovi Principales Resultados/Libros/32- Desigualdad 1151115.xlsx')
escribirCSV(documento, ruta = '/home/hugo/Documents/CSVENCOVI/')
desigualdad <- leerLibro(ruta = '/home/hugo/Documents/Encovi Principales Resultados/Libros/desigualdadCSV.xlsx')
escribirCSV(lista = desigualdad, ruta = '/home/hugo/Documents/Encovi Principales Resultados/CSV/2/')
anual()
ENC2<- cargaMasiva("/home/hugo/Documents/Encovi Principales Resultados/CSV/2/")
g1<- graficaLinea(ENC2$"2_01",rotar = "h", precision = 2)
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_01.tex",g1)
g2<- graficaLinea(ENC2$"2_02",rotar = "h",  precision = 2)
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_02.tex",g2)
g3<- graficaLinea(ENC2$"2_03",rotar = "h",  precision = 2)
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_03.tex",g3)
g4<- graficaLinea(ENC2$"2_04",rotar = "h",  precision = 2)
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_04.tex",g4)
g5<- graficaLinea(ENC2$"2_05",rotar = "h")
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_05.tex",g5)
g6<- graficaLinea(ENC2$"2_06",rotar = "h")
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_06.tex",g6)
g7<- graficaLinea(ENC2$"2_07",rotar = "h")
exportarLatex("/home/hugo/Documents/Encovi Principales Resultados/graficas/2_07.tex",g7)
